#!/usr/bin/env bash
# FUNCTION: Performs a grep using a supplied argument.
# NOTES:
#   The "-l" option makes grep print only the matching filenames.

echo 'Listing all files containing the argument you entered:'
grep -l ${1} *
