#!/usr/bin/env bash
# FUNCTION: Counts the number of files containing ${1} inside of directory ${2}.
# NOTES:
#   "-l" lists matching files, and "-r" searches recursively so no need for *
#   "|" pipes the output of grep into wc.
#   "wc" is word count, "wc -l" is line count.

printf "Number of files containing the argument you entered:"
grep -lr ${1} ${2} | wc -l
