#!/usr/bin/env bash
# FUNCTION: Counts the number of files containing the supplied argument.
# NOTES:
#   "|" pipes the output of grep into wc.
#   "wc" is word count, "wc -l" is line count.
#   "grep -l" lists matching files by line, so you can simply count the number of lines.

printf "Number of files containing the argument you entered:"
grep -l ${1} * | wc -l
