#!/usr/bin/env bash
ORIG_EXT="$1"
NEW_EXT="$2"

printf "Changing all files with extension of $ORIG_EXT to $NEW_EXT...\n"

# NOTE: In the conditional below, "1> /dev/null 2>&1" removes the output of the ls check.
# "1> /dev/null" redirects the standard output (1) to /dev/null, which discards it.
# "2>&1" redirects standard error (2) to standard output (1), which also discards it
#   (because standard output has already been redirected to /dev/null).

if ls *".$ORIG_EXT" 1> /dev/null 2>&1; then
    printf "ORIGINAL:\t"
    ls *".$ORIG_EXT"
else
    echo "No files with extension of $ORIG_EXT."
    exit 0
fi

for file in *."$ORIG_EXT"
do
    mv ./"$file" "${file%$ORIG_EXT}$NEW_EXT"
done

printf "NEW:\t\t"
ls *".$NEW_EXT"
